# Generated by Django 5.1.4 on 2024-12-15 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extensionName', models.CharField(max_length=100)),
                ('extensionReleaseDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seriesName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardName', models.CharField(max_length=100)),
                ('cardRarity', models.CharField(max_length=50)),
                ('cardIndex', models.IntegerField(verbose_name='Index in its series (ex 079/121)')),
                ('cardImage', models.URLField(verbose_name='URL which leads to an image of this card')),
                ('cardExtension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speculator.extension')),
            ],
        ),
        migrations.AddField(
            model_name='extension',
            name='extensionSeries',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speculator.series'),
        ),
    ]
